### PR TITLE
S3: Multiple Transitions in lifecycle configuration

### PR DESCRIPTION
**Pull request by ccatterina**
Hi @bblommers,
Some points about the implementation:
- I noticed that also `NoncurrentVersionTransitions` could be a list of multiple transitions so I made some changes to allow also multiple `NoncurrentVersionTransitions`.
- I added the property  `NewerNoncurrentVersions` to `NoncurrentVersionTransitions`. https://docs.aws.amazon.com/AmazonS3/latest/API/API_NoncurrentVersionTransition.html
- I've created 2 new classes `LifecycleTransition` and `LifeCycleNoncurrentVersionTransition` along the lines of `LifecycleRule` but I didn't understand exactly the purpose of `BaseModel` class. Is this approach ok?
- I added also `Transitions` and  `NoncurrentVersionTransitions` to the dict returned by `LifecyleRule.to_config_dict` but I don't understand if I need to respect some structure or properties should have predefined names.

### CODE REVIEW

**Comment by bblommers** [comment]
> I've created 2 new classes LifecycleTransition and LifeCycleNoncurrentVersionTransition along the lines of LifecycleRule but I didn't understand exactly the purpose of BaseModel class. Is this approach ok?
>

Inheriting BaseModel ensures that the classes show up on the Moto Dashboard, for people that are using the MotoServer. So it makes a lot of sense to use it here.

> I added also Transitions and NoncurrentVersionTransitions to the dict returned by LifecyleRule.to_config_dict but I don't understand if I need to respect some structure or properties should have predefined names.
>

Me neither! But if it's wrong, I'm sure somebody will complain. :)

**Review by bblommers — APPROVED** [review]
LGTM - thank you for fixing this @ccatterina!

**Comment by bblommers** [comment]
The `payment-approved` label should've created this comment automatically, but considering it didn't, I'll do it manually:

Thank you for contributing to Moto!

To show our thanks, we'd like to share some of the donations that we've received with you. PR's like this are the big reason that Moto is as successful as it is - so it's only fair that you, as a contributor, gets to share the spoils.

We've created a companion website with more information:
https://payments.getmoto.org/

Feel free to open a bug or discussion if you run into any problems:
https://github.com/getmoto/payments`

**Comment by ccatterina** [comment]
> Thank you for contributing to Moto!
> 
> To show our thanks, we'd like to share some of the donations that we've received with you. PR's like this are the big reason that Moto is as successful as it is - so it's only fair that you, as a contributor, gets to share the spoils.
> 
> We've created a companion website with more information:
> https://payments.getmoto.org/
> 
> Feel free to open a bug or discussion if you run into any problems:
> [https://github.com/getmoto/payments`](https://github.com/getmoto/payments%60)

@bblommers Thank you, I appreciate it!

**Comment by bblommers** [comment]
FYI @ccatterina, I just noticed a bug in our login-flow for https://payments.getmoto.org. I don't know if you encountered this, but if  you did - apologies! This should now be fixed.

**Comment by ccatterina** [comment]
@bblommers yes, I encountered it and I thought it was a temporary problem. Thank you! 😊

**Pull request merged**
