### PR TITLE
feat: Implementation of  memorydb api

### PR DESCRIPTION
**Pull request by archinksagar**
This is the initial moto implementation of AWS MemoryDB API.

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
Hi @archinksagar, it looks like all tests fail in ServerMode - see https://github.com/getmoto/moto/actions/runs/10778987259/job/29891829117?pr=8108

Could you also merge in the latest master? I just pushed a fix to make Moto compatible with the latest botocore, and the build for this PR may still fail if that change is not included.

**Comment by archinksagar** [comment]
@bblommers Thanks for reviewing, I merged the latest master. If the tests fail in server mode, do I need to spell out the URL paths in urls.py? Would that fix it?

**Comment by bblommers** [comment]
Hi @archinksagar, yes, manually adding the URL's usually fixes the ServerMode tests. Let me know if it doesn't, or if you run into other issues, and I can have a closer look.

**Comment by archinksagar** [comment]
@bblommers  how to I get all the correct URL paths for memorydb?

**Comment by bblommers** [comment]
@archinksagar You can run the MotoServer locally, and Moto will tell you. Within the virtual environment that you develop Moto in, run:
```
moto_server
```
And then run the tests against it:
```
TEST_SERVER_MODE=true pytest -sv tests/test_memorydb
```
The server logs will then tell you which URL's are being visited, and which requests are failing.

**Comment by archinksagar** [comment]
@bblommers Server mode tests were failing because it did not find the correct URL pattern in werkzeug_app. I added few changes to that file. Could you review again and let me know if the changes are right in werkzeug_app.py. Thankyou.

**Review by bblommers — APPROVED** [review]
This looks great - thank you @archinksagar!

**Pull request merged**
