### PR TITLE
Techdebt: Replace sure with regular assertions in RedShift

### PR DESCRIPTION
**Pull request by kbalk**
See https://github.com/getmoto/moto/issues/6035

This is the last test directory referencing the "sure" library.  

Still need to modify `test_redshift.py`, which is large and has a lot of sure usage.  Also, one of its tests is failing and I'll need to investigate:

```
=================================== FAILURES ===================================
_________________________ test_get_cluster_credentials _________________________
    @mock_redshift
    def test_get_cluster_credentials():
        client = boto3.client("redshift", region_name="us-east-1")
    
        cluster_identifier = "my_cluster"
        client.create_cluster(
            ClusterIdentifier=cluster_identifier,
            ClusterType="single-node",
            DBName="test",
            MasterUsername="user",
            MasterUserPassword="password",
            NodeType="ds2.xlarge",
        )
    
        expected_expiration = time.mktime(
            (datetime.datetime.now() + datetime.timedelta(0, 900)).timetuple()
        )
        db_user = "some_user"
        response = client.get_cluster_credentials(
            ClusterIdentifier=cluster_identifier, DbUser=db_user
        )
        response["DbUser"].should.equal(f"IAM:{db_user}")
>       assert time.mktime((response["Expiration"]).timetuple()) == pytest.approx(
            expected_expiration
        )
E       assert 1692316550.0 == 1692302150.0 ± 1.7e+03
E         comparison failed
E         Obtained: 1692316550.0
E         Expected: 1692302150.0 ± 1.7e+03

tests/test_redshift/test_redshift.py:1858: AssertionError
```

### CODE REVIEW

**Comment by bblommers** [comment]
> assert 1692316550.0 == 1692302150.0 ± 1.7e+03
>

Maybe another timezone issue?

**Comment by kbalk** [comment]
> > assert 1692316550.0 == 1692302150.0 ± 1.7e+03
> 
> Maybe another timezone issue?

I'll look into it.  When the other PRs are merged, I'll remove "sure" from `requirements-tests.txt` and rerun all tests, then commit the change to that file as well.

**Comment by kbalk** [comment]
> > > assert 1692316550.0 == 1692302150.0 ± 1.7e+03
> > 
> > 
> > Maybe another timezone issue?
> 
> I'll look into it. When the other PRs are merged, I'll remove "surer" from `requirements-tests.txt` and rerun all tests, then commit the change to that file as well.

You're correct, @bblommers, it was another timezone issue.  Rerunning all the tests at the moment, so still WIP.

**Comment by kbalk** [comment]
I fixed some pylint errors in redshift's `models.py` and that has generated some codecov issues.  Basically by separating the if/else it found that the else was never tested.   I suppose I'll need to add more unit tests to satisfy codecov.  The alternative is to re-introduce the pylint issues that moto currently doesn't care about.

**Comment by bblommers** [comment]
I don't really mind the codecov issues, @kbalk. The behaviour/logic is completely the same, from what I can see, so these changes LGTM

**Comment by kbalk** [comment]
> I don't really mind the codecov issues, @kbalk. The behaviour/logic is completely the same, from what I can see, so these changes LGTM

I feel a little guilty not adding tests, but I'm ready to finish this and move on.

**Comment by bblommers** [comment]
> but I'm ready to finish this and move on.
>

Believe me, I completely understand. 🙂 

Thank you so much for finishing this @kbalk. I can only imagine how much hours you've put into all of this, and it is very much appreciated!

**Review by bblommers — APPROVED** [review]

**Pull request merged**
