### PR TITLE
CognitoIdentity: get_credentials_for_identity() should have Expiration as number.

### PR DESCRIPTION
**Pull request by nonchan7720**
Hi.
The type of Credentials.Expiration is a timestamp number type.

ref: https://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_GetCredentialsForIdentity.html#API_GetCredentialsForIdentity_ResponseSyntax

It was discovered by a type conversion error in Golang's sdk v2.
ref: https://github.com/aws/aws-sdk-go-v2/blob/6afe5286d243f06aa040d3954b765b38366b88c2/service/cognitoidentity/deserializers.go#L3374-L3383

Thank you very much.

### CODE REVIEW

**Review by bblommers — APPROVED** [review]
LGTM - thanks @nonchan7720!

**Comment by nonchan7720** [comment]
Hi, @bblommers .

When do you plan to release these?

**Comment by bblommers** [comment]
I've just released 4.2.10 @nonchan7720!

**Comment by nonchan7720** [comment]
Thank you very match!!

**Pull request merged**
