### PR TITLE
Batch: arraySize and child jobs

### PR DESCRIPTION
**Pull request by rafcio19**
Closes https://github.com/getmoto/moto/issues/6512

### CODE REVIEW

**Comment by bblommers** [comment]
BTW, I would be happy to have a go at the implementation, I just don't know when/if I have time in the coming days.

**Comment by rafcio19** [comment]
Thanks for the tips, leave it with me for another while.

**Comment by oliver-helix** [comment]
Hey @rafcio19  @bblommers 
Thanks so much for your hard work here. Any update since July?

**Comment by rafcio19** [comment]
Hey chaps, I haven't had much time to devote to moto since the summer. If someone else wants to have a go then please do; or you could 🤞 and give me a few weeks.

**Comment by bblommers** [comment]
Hey @rafcio19, I just had a crack at it. Instead of an `ArrayJob`, I realized it was easier to just create additional regular jobs in the `submit_job`-method. The parent-job itself will not be executed, but has a list of child-jobs. 
When describing a job that happens to have any child-jobs, we can check immediately check the status of those child-jobs - so they are no longer hardcoded to 'SUCCEEDED'.

Based on my testing, this is all in-line with how AWS behaves

**Comment by rafcio19** [comment]
Go nuts @bblommers, I've had it long enough. Will try to pick up more moto issues in the near future

**Pull request merged**
