### PR TITLE
add patch baseline operations

### PR DESCRIPTION
**Pull request by pinzon**
This pr adds the operations corresponding to the SSM Patch Baseline resource.

- [x] create_patch_baseline
- [x] describe_patch_baselines
- [x] delete_patch_baseline

### CODE REVIEW

**Review by mikegrima — CHANGES_REQUESTED** [review]
Can you also update the Readme to indicate the implementation of these functions?
https://github.com/getmoto/moto/blob/master/IMPLEMENTATION_COVERAGE.md

Other than than great PR!

**Comment by pinzon** [comment]
Hi @mikegrima. thanks for the review. I updated the file as requested. :smile:

**Review by mikegrima — APPROVED** [review]

**Comment by mikegrima** [comment]
Will merge after the tests pass

**Review by bblommers — APPROVED** [review]
Thanks @pinzon!

**Pull request merged**
