### PR TITLE
CognitoIDP: clean MFA settings capability and enable multiple MFA methods

### PR DESCRIPTION
**Pull request by schmittjoaopedro**
Fix for issue #6852, with the following changes:

- add capacity to disable MFA settings and clear relaated properties
- add capacity to enable MFA with SMS and TOTP in parallel

### CODE REVIEW

**Review by bblommers — APPROVED** [review]
LGTM - thank you for fixing this @schmittjoaopedro!

**Comment by schmittjoaopedro** [comment]
Hello @bblommers 
Is there a way to release a dev version of moto with this fix? I need this to proceed with a feature I'm developing
I remember in a previous PR it created a version like so `4.1.15.dev91`

**Comment by bblommers** [comment]
That should happen automatically @schmittjoaopedro  - that's part of the `Release`-step in this workflow:
https://github.com/getmoto/moto/actions/runs/6316418820

There is a bit of a queue, so it may take a few hours..

**Comment by schmittjoaopedro** [comment]
Great, thanks

**Pull request merged**
