### PR TITLE
Feature/cw destination

### PR DESCRIPTION
**Pull request by macnev2013**
# Added
- Support for Destinations
- added support for api `GetDestination`
- added support for api `PutDestination`
- added support for api `DeleteDestination`
- added support for api `DescribeDestinations`
- added support for api `PutDestinationPolicy`

# TF_Test
- TestAccAWSCloudwatchLogDestination
  - TestAccAWSCloudwatchLogDestination_basic
  - TestAccAWSCloudwatchLogDestination_disappears
  - TestAccAWSCloudwatchLogDestinationPolicy_basic

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
```
[ltt.gotest] 2021/12/05 21:17:26 [DEBUG] [aws-sdk-go] {"StreamDescription": {"StreamARN": "arn:aws:kinesis:us-east-1:123456789012:stream/RootAccess_nqisy", "StreamName": "RootAccess_nqisy", "StreamCreationTimestamp": "2021-12-05 21:17:16.644972", "StreamStatus": "ACTIVE", "HasMoreShards": false, "RetentionPeriodHours": 24, "EnhancedMonitoring": [{"ShardLevelMetrics": []}], "EncryptionType": "NONE", "Shards": [{"HashKeyRange": {"EndingHashKey": "340282366920938463463374607431768211456", "StartingHashKey": "0"}, "SequenceNumberRange": {"StartingSequenceNumber": 0}, "ShardId": "shardId-000000000000"}]}}
[ltt.gotest] 2021/12/05 21:17:26 [DEBUG] [aws-sdk-go] DEBUG: Unmarshal Response kinesis/DescribeStream failed, attempt 1/25, error SerializationError: failed decoding JSON RPC response
[ltt.gotest] 	status code: 200, request id: 
[ltt.gotest] caused by: unsupported value: <nil> (*string)
```

Not quite sure what TF is complaining about it here - we maybe missing a response value in Kinesis

**Comment by macnev2013** [comment]
Hi @bblommers, Can we restart the build once? Could it be a flaky case?

**Comment by bblommers** [comment]
Doesn't look like it's flaky, @macnev2013 - it just failed again I'm afraid

**Comment by macnev2013** [comment]
Okay. Will take detailed look today. Thanks.

**Pull request closed without merging**
