### PR TITLE
Cloudformation: ASG parameter error

### PR DESCRIPTION
**Pull request by rafcio19**
Closes https://github.com/getmoto/moto/issues/7528

### CODE REVIEW

**Comment by rafcio19** [comment]
@bblommers I don't know why codecov is failing.  
It's been happening on a few previous PRs but a rebase from master or a re-run of CI usually cleared it, not this time though. Mine is a tiny change 🤷

**Comment by bblommers** [comment]
> Report is 143 commits behind head on master.

@rafcio19 That's why it's failing. Compared to a month ago, the codecov dropped a bit indeed. I don't know why they don't just compare to head, as that would be a more realistic diff... I'm essentially yolo-ing PR's for now, ignoring these failures (and hoping that CodeCov catches up at some point).

 ¯\\_(ツ)_/¯

**Review by bblommers — APPROVED** [review]
Thanks for the fix!

**Comment by rafcio19** [comment]
@bblommers if CodeCov continues to disappoint then running [coverage](https://coverage.readthedocs.io/en/latest/) locally would be a good substitute.

**Pull request merged**
