### PR TITLE
directconnect: MACsec associate/disassociate + LAG create/describe

### PR DESCRIPTION
**Pull request by ptgeorge**
* Additional features for Direct Connect
  * LAG create (`aws directconnect create-lag`)
  * LAGs describe (`aws directconnect describe-lags`)
  * MACsec associate (`aws directconnect associate-mac-sec-key`)
  * MACsec disassociate (`aws directconnect disassociate-mac-sec-key`)
* Corrected minor variable typo (co**nnn**ection_id vs co**nn**ection_id)
* Tests added to cover new functionality
* Linter checks passed locally
* Tests passed locally

Notes
* Scaffolding tool (scripts/scaffold.py) was used to generate code stubs
* MACsec associate/disassociate works for both "normal" connections and LAGs.

### CODE REVIEW

**Comment by ptgeorge** [comment]
Fixed (hopefully) python 3.8 lint issue.  The change works fine with 3.11 (don't have 3.8 readily available)

**Comment by ptgeorge** [comment]
Checks seem to be ephemeral failures and also unrelated to the changes.

**Comment by ptgeorge** [comment]
Merged `main` in yesterday.  Github workflows haven't ran yet...

**Comment by bblommers** [comment]
> Merged `main` in yesterday. Github workflows haven't ran yet...

Hi @ptgeorge, the workflow has to be approved by a maintainer for new contributors, and I hadn't gotten around to it yet.

Having said that: Welcome to Moto, and thank you for contributing these features!

**Review by bblommers — APPROVED** [review]

**Comment by ptgeorge** [comment]
Ah sorry first time here -- it seemed nearly automatic yesterday 😁 Thanks @bblommers !

**Pull request merged**
