### PR TITLE
Add missing override

### PR DESCRIPTION
**Pull request by wangsha**
This PR https://github.com/getmoto/moto/pull/6451/ generates a regression bug.

Step to reproduce
```
from moto.core.models import responses_mock

    if responses_mock.registered():
        # do something
```

This will throw an exception 
` AttributeError: 'CustomRegistry' object has no attribute '_responses'`

It's due to the child class misses the implementation of `registered()`

This PR fixes the issue.

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
Looks like the linter is failing @wangsha:
https://github.com/getmoto/moto/actions/runs/5761073712/job/15870085114?pr=6597

**Comment by wangsha** [comment]
@bblommers fixes pushed

**Review by bblommers — CHANGES_REQUESTED** [review]
Looks like `mypy` is unhappy with this change @wangsha: 
https://github.com/getmoto/moto/actions/runs/5962347191/job/16174318237?pr=6597

**Comment by wangsha** [comment]
@bblommers fixes pushed

**Comment by wangsha** [comment]
@bblommers fixes pushed

**Review by bblommers — APPROVED** [review]
LGTM!

**Pull request merged**
