### PR TITLE
IAM policies: allow s3 accesspoint arns

### LINKED ISSUE #6742: Allow using s3 accesspoint arns in iam policies
[S3 Accesspoints](https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-access-points.html) have arns which look like this:

```
        "Resource": "arn:aws:s3:us-west-2:123456789012:accesspoint/my-access-point"
```
and
```
        "Resource" : "arn:aws:s3:us-west-2:123456789012:accesspoint/my-access-point/object/*",
```

The current implementation does not allow specifying the region in s3 arns: https://github.com/getmoto/moto/blob/d3f5e3d68b0517be1172319087ee68c0834a157a/moto/iam/policy_validation.py#L61

Right now there is an MalformedPolicyDocument error thrown it should not throw an error.

### PR DESCRIPTION
**Pull request by thomaschaaf**
fixes #6742

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
Hi @thomaschaaf, welcome to Moto!

Looks like the tests are failing, but the overall approach for this fix looks good so far.

**Comment by thomaschaaf** [comment]
@bblommers should pass the tests now

**Comment by thomaschaaf** [comment]
@bblommers  how can I run that test locally? I don't understand what is falling.

**Comment by bblommers** [comment]
@thomaschaaf Looks like an intermittent failure, so don't worry about that

**Review by bblommers — APPROVED** [review]
LGTM - thank you @thomaschaaf!

**Pull request merged**
