### PR TITLE
Update `botocore` version specifiers

### PR DESCRIPTION
**Pull request by bblommers**
Reverts #8248 
Should work again now that botocore 1.35.46 is out (see https://github.com/boto/botocore/issues/3284)

### CODE REVIEW

**Comment by bblommers** [comment]
FYI @bpandola - it looks like this is still failing

**Comment by bpandola** [comment]
@bblommers Yeah, there are two issues (at least).  The `botocore` change contained a regression, but the new code they added breaks our `BotocoreStubber`.  I have an idea for a quick fix... not sure if it will work, though.  I'll provide a PR and some more detail in a bit.

**Comment by bpandola** [comment]
@bblommers This is still an issue with `botocore` at the moment.  I've updated my original issue in their repo with additional information.

**Comment by bblommers** [comment]
Thanks for following up on this @bpandola!

**Pull request merged**
