### PR TITLE
Techdebt: Replace sure with regular assertions in secretsmanager

### PR DESCRIPTION
**Pull request by kbalk**
See https://github.com/getmoto/moto/issues/6035

### CODE REVIEW

**Review by bblommers — APPROVED** [review]

**Comment by kbalk** [comment]
> Hi @kbalk,
> 
> Thank you for contributing to Moto!
> 
> To show our thanks, we'd like to share some of the donations that we've received with you. PR's like this are the big reason that Moto is as successful as it is - so it's only fair that you, as a contributor, gets to share the spoils.
> 
> We've created a companion website with more information: https://payments.getmoto.org/
> 
> Feel free to open a bug or discussion if you run into any problems: https://github.com/getmoto/payments

I would like to turn the payment into a contribution, but I'm having trouble figuring out how to do so.

**Comment by bblommers** [comment]
Do you mean turning it into a contribution to another OpenCollective? There is no way to do that (yet) - but if you're OK with sharing the name, we can always do that for you.

**Comment by bblommers** [comment]
Ah, gotcha. That's much appreciated.

Just to give some background: all of our income is managed by OpenCollective (OC). That includes direct donations, donations via Github, and also some of the money that we receive from [Tidelift](https://tidelift.com/) every month. 

The whole reason we registered with OC, is to redistribute this money to contributors. Contributors send us an expense, for time and effort, and the moment we approve, this, OC sends the money to them. 
The majority of the money currently comes from Tidelift, who pay us for maintaining a healthy OS project - and considering you help us keep Moto healthy, it only makes sense that you get some of the money.

You can see the budget here, including all the money going in and the expenses going out: https://opencollective.com/moto#category-BUDGET

The amounts are quite low, for now, but we're hoping that with more donations from businesses who use Moto, we can reward contributors more.

The money we would pay you is currently earmarked in https://payments.getmoto.com, to remind us that part of our OpenCollective balance is already spoken for. 

So if you want to contribute this money to Moto, you don't have to do anything. We automatically retract offers that have not been claimed after 2 months or so, and the money will go back into the big pot, ready to be offered to other contributors.

**Comment by kbalk** [comment]
Thank you for the explanation.  The donation was a bit circular ... I wanted to thank moto and moto was thanking me!  I'll let the donation go back into the community pot.

**Pull request merged**
