### PR TITLE
Create RDS test clients with fixture

### PR DESCRIPTION
**Pull request by snordhausen**
Create RDS test clients with a fixture to get rid of copy&paste code in the tests. The variable is now consistently called `client`.

### CODE REVIEW

**Comment by snordhausen** [comment]
I'll look into what's breaking the server tests, I can reproduce the issue locally.

**Comment by bpandola** [comment]
@snordhausen This may help: https://docs.getmoto.org/en/latest/docs/getting_started.html#pytest-fixtures-example-usage

**Comment by snordhausen** [comment]
Test failure seems unrelated to my changes.

@bpandola Please review again.

**Review by bpandola — APPROVED** [review]
Thanks @snordhausen

**Pull request merged**
