### PR TITLE
EC2: TransitGatewayId filter for DescribeRouteTables

### PR DESCRIPTION
**Pull request by aranjan1002**
Added filter 'transit gateway id' for the DescribeRouteTables operation

### CODE REVIEW

**Comment by aranjan1002** [comment]
Linked to issue: https://github.com/getmoto/moto/issues/7735

**Review by bblommers — CHANGES_REQUESTED** [review]
Looks like linter is failing atm @aranjan1002:
https://github.com/getmoto/moto/actions/runs/9342501679/job/25718574076

You can run `make lint` locally to verify that the formatting is correct, or run `ruff`, `pylint` and `mypy` manually - see this page: http://docs.getmoto.org/en/latest/docs/contributing/installation.html#installing-moto-locally

**Comment by aranjan1002** [comment]
@bblommers The checks passed now. Could you please see if this can be merged? Thanks.

**Review by bblommers — APPROVED** [review]
Great, thank you for adding this to Moto @aranjan1002!

**Pull request merged**
