### PR TITLE
S3: add EventBridge notification for delete object tagging

### PR DESCRIPTION
**Pull request by MikiPWata**
# Changes
- `s3/models.py`
  - added notifications.send_event  to `delete_object_tagging`
- `tests/test_s3/test_s3_eventbridge_integration.py`
  - Added a pytest for notifications.send_event

### CODE REVIEW

**Comment by MikiPWata** [comment]
Hey @bblommers !
Do you mind reviewing this PR whenever you have time?
 thanks

**Review by bblommers — CHANGES_REQUESTED** [review]
Hi @MikiPWata, this LGTM. Can you merge in the latest master? That should fix the build.

**Comment by MikiPWata** [comment]
@bblommers 
Thanks for the review!
gotcha

**Comment by MikiPWata** [comment]
@bblommers 
This should be ready!

**Review by bblommers — APPROVED** [review]
Awesome - thank you @MikiPWata!

**Pull request merged**
