### PR TITLE
Events: put_events should check if detail type, detail or source are empty

### PR DESCRIPTION
**Pull request by fernando-alves**
As discussed on #7532

### CODE REVIEW

**Comment by rafcio19** [comment]
LGTM! The tests could be simplified by using pytest's [parametrize](https://docs.pytest.org/en/7.1.x/how-to/parametrize.html) - a single test with the  payload dict passed to `Entries` as parameter. 

See a straight forward example:

https://github.com/getmoto/moto/blob/fc5421a78d51711ed6b0dfb5f0b27f40a845fa60/tests/test_batch/test_batch.py#L7

**Comment by fernando-alves** [comment]
@rafcio19 I've updated the test, is this what you had in mind?

**Comment by rafcio19** [comment]
Looks great, but needs to be approved by the boss @bblommers

**Review by bblommers — APPROVED** [review]
LGTM! The tests look much cleaner now as well, which is nice.

Thank you for fixing this @fernando-alves!

**Pull request merged**
