### PR TITLE
DynamoDB: empty update expression now returns a ValidationException

### PR DESCRIPTION
**Pull request by felixscherz**
Hi, this is intended to fix an issue with dynamodb where an emtpy update expression given to `update_item` raises an unexpected exception: https://github.com/getmoto/moto/issues/7988

### CODE REVIEW

**Comment by felixscherz** [comment]
I see some tests are failing, I'll have another look:)

**Review by bblommers — CHANGES_REQUESTED** [review]
Hi @felixscherz, thanks for opening a PR for this!

The `update_expression` can be None when calling `update_item` in `models`, which would be absolutely valid. I would suggest to add this validation in `responses.py` instead, where the request first comes in:
https://github.com/getmoto/moto/blob/856ded18148ad3a2e25458950a8dbee64f95fa40/moto/dynamodb/responses.py#L892

If the user-provided value is an empty string here, we should throw an exception - everything else can stay the same.

**Comment by felixscherz** [comment]
Ok great, thanks for the help! I will have a look at the `responses.py`

**Review by bblommers — APPROVED** [review]
Great - thank you for adding this to Moto @felixscherz!

**Pull request merged**
