### PR TITLE
Adding dynamodb support to get_resources in resourcegroupstagging api

### PR DESCRIPTION
**Pull request by ppapishe**
Currently, mock_resourcegroupstagging is not able to get the dynamodb tables created using mock_dynamodb. This PR is to add that support.

### CODE REVIEW

**Comment by ppapishe** [comment]
@bblommers , Please review the PR. 

I am not sure why the previous merge messed the format. Now the make format basically removing the empty lines in all the files.

**Comment by bblommers** [comment]
Hi @ppapishe! What version of black are you using? It has to be `black==22.3.0` - formatting it with another version would explain these changes.

I think the actual change looks fine, but I would like to see them on their own - so without the formatting stuff. :slightly_smiling_face:

**Comment by ppapishe** [comment]
> Hi @ppapishe! What version of black are you using? It has to be `black==22.3.0` - formatting it with another version would explain these changes.
> 
> I think the actual change looks fine, but I would like to see them on their own - so without the formatting stuff. 🙂

let me fix that.

**Comment by ppapishe** [comment]
> 



> > Hi @ppapishe! What version of black are you using? It has to be `black==22.3.0` - formatting it with another version would explain these changes.
> > I think the actual change looks fine, but I would like to see them on their own - so without the formatting stuff. 🙂
> 
> let me fix that.

@bblommers create a new PR was easier and faster 
https://github.com/getmoto/moto/pull/7471

Closing this PR. Thanks for the comment

**Pull request closed without merging**
